name: pdfrx_coregraphics
description: CoreGraphics-backed Pdfrx engine layer for Apple platforms.
version: 0.1.1
homepage: https://github.com/espresso3389/pdfrx

environment:
  sdk: '>=3.9.0 <4.0.0'
  flutter: '>=3.29.0'
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  pdfrx_engine: ^0.1.21
  http: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: PdfrxCoregraphicsPlugin
        sharedDarwinSource: true
      macos:
        pluginClass: PdfrxCoregraphicsPlugin
        sharedDarwinSource: true
